version: "3"
services:
  web:
    container_name: web
    image: httpd
    ports:
      - "80:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: minio.apache.access
    depends_on:
      - fluentd

  fluentd:
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    command: ['server', '/data', '--address', ':9000', '--console-address', ':9001']
    # TODO: Change the these keys because of default values
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio:/data
